spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.204:3306/auth_test?autoReconnect=true&useSSL=false
    username: ${AUTH_DB_PWD:simu}
    password: ${AUTH_DB_USER:simu123}
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: localhost
    password: pass
    timeout: 3000
    port: 6379

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

